# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import zcy_md.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160530_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', zcy_md.models.MarkdownField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
